### ISSUE TITLE
ASP MVC or Core

### ISSUE THREAD

**Issue by weedkiller** [PoweredSoft/DynamicQuery#2]
hi can we get a sample so we can learn from it, in ASP MVC or Core

**Comment by dlebee** [comment]
Sure, i am currently building the sample for my self so i should release some kind of nuget package for asp.net core during the current month probably.

**Comment by dlebee** [comment]
@weedkiller  here is the sample, create an issue inside the sample if you have any questions :)

https://github.com/PoweredSoft/DynamicQueryAspNetCoreSample

**Comment by weedkiller** [comment]
you rock - go high five ✋

**Comment by dlebee** [comment]
> you rock - go high five ✋

Glad it worked out for you, if you have any questions create an issue in the sample it self, I will close the issue :)
